# Site
name: "Heavy Ion Experiment"
title: "Heavy Ion Experiment"
description: "this is description"
meta_description: "mtea_description"
logo: 'assets/images/nnew_logo.png'
favicon: 'assets/images/favicon-16x16.png'
paginate: 12
url: 'https://dorong12.github.io/'
baseurl: '/'
email: 'lsyeong99@sju.ac.kr'
#google_analytics: 'UA-46278016-1'
#disqus: 'demowebsite'
#sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  Yongsun Kim:
    name: Yongsun Kim
    display_name: Yongsun Kim
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: 
    web: 
    twitter: 
    description: "He is the king"
  Geunwoo Kim:
    name: Geunwoo Kim
    display_name: etc
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 
    web: 
    twitter: 
    description: "Ph.D"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
